apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hpq21naz8-go 
  janus-idp.io/tekton: hpq21naz8-go
  backstage.io/kubernetes-id: hpq21naz8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpq21naz8-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  