apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hpq21naz8-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hpq21naz8-go 
  name: hpq21naz8-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hpq21naz8-go 
